# Project-wide Gradle settings.

# Menggunakan JBR melalui junction untuk menghindari spasi di path (fix jlink error)
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr

# JVM Arguments
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

org.gradle.parallel=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true

ksp.incremental=false
ksp.incremental.log=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
